# -*- coding: utf-8 -*-
"""1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DicQKSp9EXwAOW8dlftpoy0z7jU968Fd
"""

import random
import math

#指数分布に従う乱数
def rand_exp(lam):
  u = random.random() #(0, 1)の乱数を生成
  x = -1/lam * math.log(1-u)
  return u

#一様分布に従う乱数
def rand_uni(a, b):
  u = random.random() #(0, 1)の乱数を生成
  x = a + u * (b - a)
  return x

#パレード分布に従う乱数
def rand_par(xm, alpha):
  u = random.random() #(0, 1)の乱数を生成
  x = xm / ((1 - u)**(1 / alpha))
  return x


N = 100000
kind ="exp"
lam = 2.0

xm = 1.0
alpha = 10.0

a = 1
b = 5

data = [0.0] * N

for i in range(N):

  if kind == "exp":
    data[i] = rand_exp(lam)
  elif kind =="uni":
    data[i] = rand_uni(a, b)
  elif kind == "par":
    data[i] = rand_par(xm, alpha)

y = [0.0] * N
x = [0.0] * N
i = 0
sum = 0.0
for d in sorted(data):
  y[i] = 1 - i / N
  x[i] = d
  print(x[i], y[i])
  sum = sum + x[i]
  i += 1

#ave = sum / N

#print (ave, sum)



import matplotlib.pyplot as plt
import math

## 描画
n_r = 1    # 行数
n_c = 1    # 列数
fig, axes = plt.subplots(n_r, n_c, tight_layout = True)    # figure オブジェクトの取得

axes.plot(x, y, '-',  label = kind, clip_on=False)


axes.legend()                 #  注釈の作成

axes.set_ylabel('CCDF')  # y 軸のラベルを描画
axes.set_xlabel('x')        #   x 軸のラベルを描画

#axes.set_xscale('log')        #   x 軸を対数目盛に変更
axes.set_yscale('log')        #   y 軸を対数目盛に変更

## グラフの保存
fig.savefig("test.png")