# -*- coding: utf-8 -*-
"""2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQhO_w1JbzypVEAsKosfZIAP7KGjKR4_
"""

import random
import math
import matplotlib.pyplot as plt

def rand_exp(lam):
  u = random.random() #(0, 1)の乱数を生成
  rnd = -1/lam * math.log(1-u)

  return rnd

def calc_poisson(Nk, lam, T = 1):

  P = [0.0] * (Nk + 1)
  P[0] = math.exp(-lam * T)
  for k in range(Nk):
      P[k + 1] = P[k] * (lam * T) / (k + 1)

  return P

lam = 10.0

Tend = 100     # シミュレーション終了時刻
t = 0         # 現在の時刻

arrivals = [0] * (Tend + 10)

#random.seed(1)

while t < Tend:
  # 客の発生
  d = rand_exp(lam) # 指数分布に従う乱数を1つ取り出す
  t = t + d #　次の客の到着時刻を計算
  arrivals[int(t)] += 1
  #print(t)

Nk = 150
B = [0] * Nk

for i in range(Tend):
  #print(i, arrivals[i])
  B[arrivals[i]] += 1

print()
P = calc_poisson(Nk, lam)
for k in range(Nk):
  B[k] /= Tend
  #print(k, B[k], P[k])

plt.plot(range(Nk), B[0:Nk],'b-', label='Simulation')
plt.plot(range(Nk), P[0:Nk], 'r-', label='Poisson Distribution')
plt.xlabel('Number of Arrivals')
plt.ylabel('Probability')
plt.title('Frequency Distribution of Arrivals')
plt.legend()
plt.show()